CREATE TABLE IF NOT EXISTS Config (
    userId INTEGER PRIMARY KEY DEFAULT NULL,
    logFalls BOOLEAN NOT NULL DEFAULT 1,
    routLogInterval TEXT NOT NULL DEFAULT '24:00:00',
    emailLogs BOOLEAN NOT NULL DEFAULT 1,
    emailInterval TEXT NOT NULL DEFAULT '720:00:00',
    alertEmailFalls  BOOLEAN NOT NULL DEFAULT 1,
    alertSMSFalls BOOLEAN NOT NULL DEFAULT 0
);
INSERT INTO Config 
VALUES (1, 1,'12:00:00',1,'720:00:00',1,0);