CREATE TABLE IF NOT EXISTS Config (
    userId INT(11) PRIMARY KEY AUTO_INCREMENT,
    logFalls BOOLEAN NOT NULL DEFAULT 1,
    routLogInterval TIME NOT NULL DEFAULT '24:00:00',
    emailLogs BOOLEAN NOT NULL DEFAULT 1,
    emailInterval TIME NOT NULL DEFAULT '720:00:00',
    alertEmailFalls  BOOLEAN NOT NULL DEFAULT 1,
    alertSMSFalls BOOLEAN NOT NULL DEFAULT 0
);
INSERT INTO Config 
VALUES (1, 1,'12:00:00',1,'720:00:00',1,0);